calculate:add.o sub.o multi.o calculate.o
	g++ add.o sub.o multi.o calculate.o -o calculate 

add.o:add.cpp
	g++ -c add.cpp -o add.o

sub.o:sub.cpp
	g++ -c sub.cpp -o sub.o

multi.o:multi.cpp
	g++ -c multi.cpp -o multi.o

calculate.o:calculate.cpp
	g++ -c calculate.cpp -o calculate.o

clean:
	rm -f *.o *.out