#使用便利
OBJ=add.o sub.o multi.o calculate.o
TARGET=calculate

${TARGET}:${OBJ}
	g++ ${OBJ} -o ${TARGET} 

add.o:add.cpp
	g++ -c add.cpp -o add.o

sub.o:sub.cpp
	g++ -c sub.cpp -o sub.o

multi.o:multi.cpp
	g++ -c multi.cpp -o multi.o

#这里将calculate.cpp也事先编译为了.o文件
calculate.o:calculate.cpp
	g++ -c calculate.cpp -o calculate.o

clean:
	rm -f *.o *.out